# Generated by Django 4.2 on 2023-05-03 20:34

from django.db import migrations, models
import django.db.models.deletion
import explorer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=65535)),
                ('folders', models.ManyToManyField(to='explorer.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modpack',
            fields=[
                ('folder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='explorer.folder')),
            ],
            bases=('explorer.folder',),
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=65535)),
                ('category', models.ForeignKey(on_delete=models.SET(explorer.models.get_uncategorised_category), to='explorer.category')),
                ('mods', models.ManyToManyField(to='explorer.mod')),
                ('tags', models.ManyToManyField(to='explorer.tag')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='mods',
            field=models.ManyToManyField(to='explorer.mod'),
        ),
    ]
