# Generated by Django 4.2 on 2023-06-09 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modpack.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', max_length=65536)),
                ('folders', models.ManyToManyField(to='modpack.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', max_length=65536)),
                ('link', models.URLField()),
                ('category', models.ForeignKey(default=modpack.models.get_uncategorised_category, on_delete=models.SET(modpack.models.get_uncategorised_category), to='modpack.category')),
                ('folders', models.ManyToManyField(to='modpack.folder')),
                ('mods', models.ManyToManyField(to='modpack.mod')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Modpack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', max_length=65536)),
                ('collaborators', models.ManyToManyField(related_name='collaborators', to=settings.AUTH_USER_MODEL)),
                ('folders', models.ManyToManyField(to='modpack.folder')),
                ('mods', models.ManyToManyField(to='modpack.mod')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mod',
            name='tags',
            field=models.ManyToManyField(blank=True, to='modpack.tag'),
        ),
        migrations.AddField(
            model_name='folder',
            name='mods',
            field=models.ManyToManyField(to='modpack.mod'),
        ),
    ]
