# Generated by Django 4.2 on 2023-05-09 18:41

from django.db import migrations, models
import modpack.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', max_length=65536)),
                ('category', models.ForeignKey(default=modpack.models.get_uncategorised_category, on_delete=models.SET(modpack.models.get_uncategorised_category), to='modpack.category')),
                ('mods', models.ManyToManyField(to='modpack.mod')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Modpack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', max_length=65536)),
                ('folders', models.ManyToManyField(to='modpack.modpack')),
                ('mods', models.ManyToManyField(to='modpack.mod')),
            ],
        ),
        migrations.AddField(
            model_name='mod',
            name='tags',
            field=models.ManyToManyField(blank=True, to='modpack.tag'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', max_length=65536)),
                ('folders', models.ManyToManyField(to='modpack.folder')),
                ('mods', models.ManyToManyField(to='modpack.mod')),
            ],
        ),
    ]
