# Generated by Django 4.2 on 2023-06-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modpack', '0003_mod_requirements_alter_modpack_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='folders',
            new_name='subfolders',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='mods',
            new_name='submods',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='folders',
            new_name='subfolders',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='mods',
            new_name='submods',
        ),
        migrations.RenameField(
            model_name='modpack',
            old_name='folders',
            new_name='subfolders',
        ),
        migrations.RenameField(
            model_name='modpack',
            old_name='mods',
            new_name='submods',
        ),
    ]
